server:
  port: 8080


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    ##### jdbc配置
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.96.66.74:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Mayj123456!
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  redis:
    host: 47.96.66.74
    password: myj618
    port: 6379
    database: 6
    timeout: 30000
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0

#RabbitMQ基本配置
  rabbitmq:
    addresses: 47.96.66.74:5672
    username: mayj
    password: mayj618
#    virtual-host: /
    connection-timeout: 15000
    publisher-returns: true
#    RabbitMQ Consumer相关配置
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        #配置签收模式，此处为手动签收
        acknowledge-mode: manual
        prefetch: 1
        retry:
          initial-interval: 1000
#    RabbitMQ Producer相关配置
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null


#上传文件及请求大小配置
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 300MB
      enabled: true
# accessKeyId
aliyun:
  sms:
    accessKeyId: LTAI4xxxxxxxxxxV9B
  # accessKeySecret
    accessKeySecret: LTAI4xxxxxxxxxxV8V9B
  # 短信模板Code
    templateCode: SMS_xxxxx74